"""Data models package.

This package contains all Pydantic models and enums for the scheduler.
Models are organized by domain for maintainability.
"""

# Re-export all models from submodules
from swarmpilot.scheduler.models.core import (
    Instance,
    InstanceStats,
    Task,
    TaskTimestamps,
)
from swarmpilot.scheduler.models.queue import (
    InstanceQueueBase,
    InstanceQueueExpectError,
    InstanceQueueProbabilistic,
)
from swarmpilot.scheduler.models.requests import (
    InstanceDrainRequest,
    InstanceRedeployRequest,
    InstanceRegisterRequest,
    InstanceRemoveRequest,
    PredictorPredictRequest,
    PredictorTrainRequest,
    StrategySetRequest,
    TaskMetadataUpdate,
    TaskResubmitRequest,
    TaskResultCallbackRequest,
    TaskSubmitRequest,
    TaskUpdateMetadataRequest,
)
from swarmpilot.scheduler.models.responses import (
    ErrorResponse,
    HealthErrorResponse,
    HealthResponse,
    HealthStats,
    InstanceDrainResponse,
    InstanceDrainStatusResponse,
    InstanceInfoResponse,
    InstanceListResponse,
    InstanceRedeployResponse,
    InstanceRegisterResponse,
    InstanceRemoveResponse,
    PredictorModelsResponse,
    PredictorPredictResponse,
    PredictorStatusResponse,
    PredictorTrainResponse,
    StrategyGetResponse,
    StrategyInfo,
    StrategySetResponse,
    SuccessResponse,
    TaskClearResponse,
    TaskDetailInfo,
    TaskDetailResponse,
    TaskInfo,
    TaskListResponse,
    TaskRepredictResponse,
    TaskResubmitResponse,
    TaskResultCallbackResponse,
    TaskScheduleInfo,
    TaskScheduleInfoResponse,
    TaskSubmitResponse,
    TaskSummary,
    TaskUpdateMetadataResponse,
    TaskUpdateMetadataResult,
)
from swarmpilot.scheduler.models.status import (
    InstanceStatus,
    StrategyType,
    TaskStatus,
    WSMessageType,
)
from swarmpilot.scheduler.models.websocket import (
    WSAckMessage,
    WSErrorMessage,
    WSPingMessage,
    WSPongMessage,
    WSTaskResultMessage,
)

__all__ = [
    "ErrorResponse",
    "HealthErrorResponse",
    "HealthResponse",
    "HealthStats",
    "Instance",
    "InstanceDrainRequest",
    "InstanceDrainResponse",
    "InstanceDrainStatusResponse",
    "InstanceInfoResponse",
    "InstanceListResponse",
    "InstanceQueueBase",
    "InstanceQueueExpectError",
    "InstanceQueueProbabilistic",
    "InstanceRedeployRequest",
    "InstanceRedeployResponse",
    "InstanceRegisterRequest",
    "InstanceRegisterResponse",
    "InstanceRemoveRequest",
    "InstanceRemoveResponse",
    "InstanceStats",
    "InstanceStatus",
    "PredictorModelsResponse",
    "PredictorPredictRequest",
    "PredictorPredictResponse",
    "PredictorStatusResponse",
    "PredictorTrainRequest",
    "PredictorTrainResponse",
    "StrategyGetResponse",
    "StrategyInfo",
    "StrategySetRequest",
    "StrategySetResponse",
    "StrategyType",
    "SuccessResponse",
    "Task",
    "TaskClearResponse",
    "TaskDetailInfo",
    "TaskDetailResponse",
    "TaskInfo",
    "TaskListResponse",
    "TaskMetadataUpdate",
    "TaskRepredictResponse",
    "TaskResubmitRequest",
    "TaskResubmitResponse",
    "TaskResultCallbackRequest",
    "TaskResultCallbackResponse",
    "TaskScheduleInfo",
    "TaskScheduleInfoResponse",
    "TaskStatus",
    "TaskSubmitRequest",
    "TaskSubmitResponse",
    "TaskSummary",
    "TaskTimestamps",
    "TaskUpdateMetadataRequest",
    "TaskUpdateMetadataResponse",
    "TaskUpdateMetadataResult",
    "WSAckMessage",
    "WSErrorMessage",
    "WSMessageType",
    "WSPingMessage",
    "WSPongMessage",
    "WSTaskResultMessage",
]
